[package]
name = "rust-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
hi = { version = "0.1.0", path = "plugins/hi" }
kovi = "0.11.5"

[workspace]
members = ["plugins/hi"]

[workspace.dependencies]
kovi = "0.11.5"
